# Generated by Django 4.1 on 2023-04-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='street_address1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='street_address2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='town_or_city',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
