# Generated by Django 4.2 on 2023-04-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgresql_db', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
