# Generated by Django 4.1 on 2023-04-27 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_has_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inventory_count',
        ),
    ]
